-- 코드를 입력하세요
-- 음식 종류별로 묶고
-- 그 중에서 즐겨찾기수의 최대값을 갖는 식당 출력
-- 정렬 : 음식 종류 내림차순
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN (
    SELECT FOOD_TYPE, MAX(FAVORITES)
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC;