-- 코드를 입력하세요
-- INS일 때는 중성화 X인데, OUTS일 때 중성화 O인 동물 출력
SELECT INS.ANIMAL_ID, INS.ANIMAL_TYPE, INS.NAME
FROM ANIMAL_INS INS
JOIN ANIMAL_OUTS OUTS
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE INS.SEX_UPON_INTAKE LIKE 'Intact%'
AND OUTS.SEX_UPON_OUTCOME IN ('Neutered Male', 'Spayed Female');