-- 코드를 입력하세요
-- 생일이 3월인 여성 (GENDER 여성, DATE_OF_BIRTH 3월) => WHERE절
-- ID, NAME, GENDER, DATE_OF_BIRTH 조회
-- TLNO가 NULL이 아닌 데이터만 -> WHERE절
-- ID기준 오름차순
SELECT
MEMBER_ID,
MEMBER_NAME,
GENDER,
DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE DATE_FORMAT(DATE_OF_BIRTH, '%m') = '03' AND GENDER = 'W' AND TLNO IS NOT NULL
ORDER BY MEMBER_ID;