-- 보호 시작일보다 입양일이 더 빠른 동물의 아이디와 이름 조회
-- INS와 OUTS에서 DATETIME을 비교하고
-- OUTS가 INT보다 더 먼저 있는 데이터를 보여준다.
-- INNER JOIN 건 다음에 WHERE절로 조건 걸면 된다.
SELECT INS.ANIMAL_ID, INS.NAME
FROM ANIMAL_INS INS
JOIN ANIMAL_OUTS OUTS
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE INS.DATETIME > OUTS.DATETIME
ORDER BY INS.DATETIME ASC;
