-- 세단 중에서
-- 10월에 대여를 한 적 있는 자동차 리스트 출력
SELECT DISTINCT(H.CAR_ID)
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN CAR_RENTAL_COMPANY_CAR C
ON H.CAR_ID = C.CAR_ID
WHERE MONTH(H.START_DATE) = 10
AND C.CAR_TYPE = '세단'
ORDER BY H.CAR_ID DESC;