-- 코드를 입력하세요
-- 두 개의 테이블을 게시글 ID로 먼저 묶는다.
-- 단 게시글은 22년도 10월에 작성된 것으로
-- 댓글 작성일 기준 오름차순 정렬, 게시글 제목으로 오름차순
SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_REPLY R
ON B.BOARD_ID = R.BOARD_ID
WHERE DATE_FORMAT(B.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC;